[gameContainer] to appease vercel. [11:20am]
heres my deploy error code: 

Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry
info  - Linting and checking validity of types...
Failed to compile.
./components/GameContainer.tsx:16:21
Type error: Cannot find module 'components/FamilyTreeContainer2' or its corresponding type declarations.
  14 | import Container from 'react-bootstrap/Container'
  15 | import Family from 'components/FamilyTreeContainer1'
> 16 | import Family2 from 'components/FamilyTreeContainer2'
     |                     ^
  17 | import GameCounter from 'components/GameCounter'
  18 | import GameChild from 'components/GameChild'
  19 | 
Error: Command "npm run build" exited with 1