ES6: getter-method & data-return method [9:25am]
arguably frowned upon i'm sure theres a better way to do this.
i hear thats a feature. not a flaw of typescript that you can do javascript in it so i am doing this way in spite of there being better practices.

my go-around to:

class Call {
        constructor(url) { let url = this.url } 
}

Getting error TS2339: Property does not exist on type for a valid ES6 class #6373

a working go-around to this error is not using ES6 classes at all and using normal conditional-logic based modularized functions to handle:
accepting [method:string, url:string, data:string] as data.String args that dictate either: (ajax, axios, fetch) to handle data call.

I already wonder about fetch being iffy having seen that fetch is a special keyword in next.js that works differently in
 getStaticProps() & related server-side/behind-the-scene/pre-build functionality than other data calls.