[strain] dummy prop for now. TS err [1:35am]
i wonder if there's a tsconfig.json key that can ignore this error:

Type '{ dummyProp: string; clickedStrain: string; setClickedStrain: Dispatch<SetStateAction<string>>; }' is not assignable to type 'IntrinsicAttributes'.
  Property 'dummyProp' does not exist on type 'IntrinsicAttributes'.ts(2322)

<StrainDisplay                  
                  dummyProp={'dummypropstring'}
                  clickedStrain={clickedStrain} setClickedStrain={setClickedStrain}       
                  />

for now... whatever first prop i have there is returning an error:

clickedStrain={clickedStrain} setClickedStrain={setClickedStrain}        

so instead of just having these 2 state related functions be the only ones. A new prop that is diverting the error from the needed methods is set before the others.