Add files via upload
verify that my constructor class would be working in a normal javascript file.
the tsconfig.json alterations did nothing to allow for [this.url] to be accepted  

NonErrorEmittedError: (Emitted value instead of an instance of Error) 
  x await isn't allowed in non-async function

the getter methods housed within a class constructor,  when wrapped in an async function are similar to:

object.forEach( (data) => {                         // expressions need to be redeclared as async over here. 
         let newdata = await data 
}